---
title: "First steps with the pryam package"
---

This article demonstrates some of the operations from the first steps tutorial from the pyam package, *but from R*.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pryam)
```

```{r}
df <- pyam_data_frame(system.file("extdata", "pyam", "tutorial_data.csv", package = "pryam"))
```

Printing:
```{r}
df
```

Index values:
```{r}
df$model
```

```{r}
df$scenario
```

```{r}
df$scenario
```

```{r}
df$region
```

```{r}
df$variables(include_units = TRUE)
```

## Apply filters to the ensemble and display the timeseries data

```{r}
df$filter(model = "MESSAGE")$scenario
```

```{r}
df$filter(model = "MESSAGE*")$scenario
```

```{r}
df$filter(region = "World", keep = FALSE)$region
```

## Filtering by variables and levels

```{r}
df$filter(variable='Primary Energy*', level=1)$variable
```

```{r}
df$filter(variable='Primary Energy*', level='1-')$variable
```

## Visualize the timeseries data using the plotting library

```{python}
r.df.filter(variable='Emissions|CO2', region='World').plot()
```

